spring.application.name=ProdBackend
server.port = 8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring-doc.swagger-ui.path=/docs


jwt.access-token.expiration.ms=1200000
jwt.refresh-token.expiration.sec=604800